### ISSUE TITLE
pxbee_ota_update for posix

### ISSUE THREAD

**Issue by ggkitsas** [digidotcom/xbee_ansic_library#10]
Hello,

Would it be possible to support the pxbee_ota_update utility for POSIX systems?

**Comment by tomlogic** [comment]
It's supposed to work, but it looks like there might be some Makefile problems.  I'll see if I can get it to build, but I don't have hardware handy to test it.

Keep in mind that this is for updating the Freescale HCS08 application (32K flash) on a Programmable XBee module.  Is that what you're looking for?  It's not for installing standard XBee firmware on the radio processor.

**Comment by tomlogic** [comment]
Closing issue due to lack of response.
