### ISSUE TITLE
"Error -110 waiting for query to complete"

### ISSUE THREAD

**Issue by jiliao7456** [digidotcom/xbee_ansic_library#18]
When I try to use the "gpm" sample, I get an error after "Waiting for driver to query the Xbee Device..." :
Error -110 waiting for query to complete.
And then, none of the command get a success.
However, once I open XCTU and add this device, the problem will be solved.
I wonder how could I use Xbee C Library sample without open XCTU?

**Comment by jiliao7456** [comment]
I am afraid it is related to " Opens the communication with the XBee device". How to do it in C langurage?

**Comment by tomlogic** [comment]
What platform (Windows, Linux, Mac)?  What baud rate (default is 115200)?  Have you configured the module with ATAP=1?  Does the `atinter` sample work?  Note that `gpm` is only available on a few modules (XBee S6B/Wi-Fi is the only one I know of for sure).  Does `xbee_term` work?

**Comment by jiliao7456** [comment]
Thank you for your reply. The platform is Linux and baud rate is 115200, ATAP = 1.  atinter and xbee_term samples also do not work.

**Comment by qxy12** [comment]
I have met the same problem,did you solved it?

**Comment by jiliao7456** [comment]
> I have met the same problem,did you solved it?

Yes, that is due to series port configuration problem. In my code, I configured my series port as XCTU did and solved the problem.

**Comment by qxy12** [comment]
thanks for you answer, Can you tell me the specific port configuration ?

**Comment by jiliao7456** [comment]
> thanks for you answer, Can you tell me the specific port configuration ?

No problem. When you enter command "stty -F /dev/ttyUSB* -a", the output should be shown as follows:
`speed 9600 baud; rows 0; columns 0; line = 0;
intr = <undef>; quit = <undef>; erase = <undef>; kill = <undef>; eof = <undef>;
eol = M-&; eol2 = <undef>; swtch = M-P; start = ^Q; stop = ^S; susp = ^W;
rprnt = ^?; werase = <undef>; lnext = <undef>; discard = <undef>;
min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread clocal -crtscts
ignbrk -brkint ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff
-iuclc -ixany -imaxbel -iutf8
-opost -olcuc -ocrnl -onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
-isig -icanon -iexten -echo -echoe -echok -echonl -noflsh -xcase -tostop -echoprt
-echoctl -echoke -flusho -extproc`

**Comment by tomlogic** [comment]
If anyone identifies settings from that list that fix their problems, please report it here an re-open this issue.  I can then look into updating the serial driver to incorporate those changes.

**Comment by tomlogic** [comment]
Note to anyone following this issue: I recently pushed changes/improvements to the POSIX serial library that make use of `cfmakeraw()`, which hopefully resolves outstanding serial issues for POSIX users.
