### ISSUE TITLE
needed material to test the code 

### ISSUE THREAD

**Issue by touzi95** [digidotcom/xbee_ansic_library#20]
Hello,

I am new to ZigBee, I just wanna know which material is needed to test this code ( the ZigBee material ) on my Linux pc.

Thank you for helping me with my school project:).

**Comment by touzi95** [comment]
help help help please !

**Comment by tomlogic** [comment]
You need an XBee module and a USB interface board.  I believe an XBee S2B or S2C would work, and probably the new XBee3 Zigbee.  There's a sample called `zigbee_walker` that will use ZDO/ZDP and ZCL protocols to enumerate clusters and attributes of a device and display their values.

But you'll need to find a Zigbee device to communicate with, and figure out how to get them to connect.

Or if you're just looking to do wireless communications between two or more Linux devices, you can create an XBee-only network and use something like the `transparent_client` to send messages between them.
