### ISSUE TITLE
I wan Use the Modules Xbee 900HP With this library on Arduino? 

### ISSUE THREAD

**Issue by dev-nicolasv** [digidotcom/xbee_ansic_library#21]
Hello I'm Nicolas, I need your help... 
I want connect with API mode the Xbee 900HP with Arduino.. it is posible?

**Comment by tomlogic** [comment]
There isn't an official port of the library to Arduino.  I think one limitation has been that there isn't a standard hardware interface for an XBee module that includes hardware flow control (CTS/RTS lines).
