### ISSUE TITLE
Wating for remote incoming packet function

### ISSUE THREAD

**Issue by theanhhoang** [digidotcom/xbee_ansic_library#23]
Hi,
I am testing the library with sample code. However, I have not found any sample code that waiting for a remote incoming packet and then do the callback. Is any function in the library that does this job?
Thanks!

**Comment by tomlogic** [comment]
Take a look at the "transparent client" sample (`samples/common/transparent_client.c`), available on both POSIX and Win32 platforms.  It shows two different methods, one for when `ATAO=0` (using a frame handler for all 0x90 frames) and one for `ATAO != 0` that uses an endpoint/cluster table for dispatching messages based on the destination endpoint and cluster.
