### ISSUE TITLE
What function should I call to get the "Device ID" from an end node when using an XBee module as coordinator?

### ISSUE THREAD

**Issue by m4l490n** [digidotcom/xbee_ansic_library#25]
This is not an issue but there is no "questions" or "support" section.

I have an application where I have an XBee module acting as coordinator and I'm using this library with it. The problem is that I need to be able to identify the devices connected to it and I need to do that by getting their Device ID's. I haven't been able to identify a function to call from this library that would help me get the Device IDs of the end devices and routers connected to my coordinator.

Is there a way to do this?

Thanks!

**Comment by tomlogic** [comment]
Take a look at the `transparent_client` sample.  It demonstrates use of `src/xbee/xbee_discovery.c` via code in `samples/common/_nodetable.c` to discover devices on the network.  You can link `_nodetable.c` directly into your program to make use of its APIs, or use it as a starting point for your own node table management.  The node table holds the 64-bit IEEE address, 16-bit network address, and the remote devices `ATNI` value.
