### ISSUE TITLE
Rust bindings/wrapper

### ISSUE THREAD

**Issue by reinhardknoll** [digidotcom/xbee_ansic_library#28]
It would be great if this C library could be wrapped to provide a separate Rust interface.

**Comment by tomlogic** [comment]
I'm all for someone forking the library and adding Rust wrappers.  I personally haven't done any Rust programming, so I wouldn't be qualified to review a PR with Rust wrappers.  The goal of the library was for it to be portable to any ANSI C platform, including many embedded targets (at one time it was running its ZCL stack on an 8-bit processor with 24KB of flash).

But if a Rust fork was out there, I'd be willing to update the README to point to it.

**Comment by mikewadsten** [comment]
I would imagine that this could be done separately using something like [bindgen](https://rust-lang.github.io/rust-bindgen/).
