### ISSUE TITLE
STM32 Porting

### ISSUE THREAD

**Issue by rezasgpco** [digidotcom/xbee_ansic_library#29]
Hi
Good time

I am need the directory, contain headers and source code files, for using the Digi XBee ANSI C Library on STM32 Platform (such as STM32F1xxx using keil uvision IDE).

I'll need to headers and source code files :
- xbee_platform_stm32.c
- xbee_serial_stm32.c
- platform_config.h

Is it possible to write and add these files for the STM32 platforms?
I need these files to port the Digi XBee ANSI C library to the STM32 microcontroller.

Thank you.

**Comment by tomlogic** [comment]
Yes, it is possible to write and add those files for the STM32 platform.

Take a look at https://github.com/digidotcom/xbee_ansic_library/blob/master/ports/README.md for instructions on how you can create them.  If you're uncertain about how to define a macro in the platform header, or the functionality of a given platform function, you can reference the other platforms to see how they operate.

**Comment by Thetatronics** [comment]
@rezasgpco  Did you ever complete this porting?  If so, could you post your solution or provide it as a pull request?

**Comment by mpieper** [comment]
I was wondering, given the license, why there wasn't one out there already...  Then I dug and voila: https://github.com/sufst/xbee_ansic_library

Note that their implementation uses ThreadX for its timing functions.  You should be able to modify it quickly to your needs.

p.s. If anyone knows an easy way to search through forks of a specific repo (e.g. this one) I'd love to know.  I had to manually open ~7 of them and search commits until i found sufst's fork.

**Comment by tomlogic** [comment]
On any GitHub project, if you go to "Insights" and the "Network", you'll see who's making commits on their forks.

Here's the [network](https://github.com/digidotcom/xbee_ansic_library/network) for this project.

**Comment by tomlogic** [comment]
I'm closing this out as we haven't received a pull request to integrate anyone's STM32 port.
