### ISSUE TITLE
Compile Error Linux make: *** [../common/common.mk:103: ipv4_client] Error 1

### ISSUE THREAD

**Issue by aylashiv** [digidotcom/xbee_ansic_library#37]
Hi Digi,

I'm trying to compile the XBee C SDK on a Linux machine, the error is throwing as follows,

![Screenshot from 2024-02-21 16-52-23](https://github.com/digidotcom/xbee_ansic_library/assets/32709434/59fd4afc-ce1f-4c14-9535-b6a4429cb3d4)
 
Could you help me to resolve the same, the machine is ARM-32 Cortex-A8 AM335X.

Thanks,
Shiva.A

**Comment by tomlogic** [comment]
I think that changing the declaration of `_ttystate_orig` in both `ports/posix/xbee_readline.c` and `samples/posix/xbee_term_posix.c` to include the `static` keyword should address that linking error.

`static struct termios _ttystate_orig;`

I was unable to reproduce the linker error in a test compile on macOS, but adding `static` didn't cause any compiler errors.

If that fixes your problem, I'll push a fix up to the repository.  Thanks for reporting it.

**Comment by aylashiv** [comment]
Solved!! Thanks.
