### ISSUE TITLE
How do I define a VERBOSE macro when building?

### ISSUE THREAD

**Issue by aylashiv** [digidotcom/xbee_ansic_library#39]
Hi,
I 'm debugging the XBee remote_at code in common codes, where i have issued some console prints in Xbee_device.c file, but i'm unable to print the same. I'm using the xbee_dev_tick() function.

Thanks,
Shiva.A###

**Comment by tomlogic** [comment]
You'll need to provide some more details.  The `xbee_device.c` file refers to the local, serially-connected XBee module.

It sounds like you're using the `remote_at` sample program.  Does that sample work as expected, when used with an unmodified `xbee_device.c`?

As for the failure, what are you expecting to see, and what are you seeing instead?  Where are you adding console prints in `xbee_device.c`?  What isn't printing?

Are you expecting fields of the `xbee_dev_t` structure to change?

**Comment by samhitha-emb** [comment]
Exactly.. Using remote_at Sample common Program, Yes the Sample Works expected wihout modifying the xbee_device.c File, I want to Enable XBEE_DEVICE_VERBOSE in xbee_device.c source file were i'm unable to do and want to have console prints in xbee_frame_dump_modem_status() function, I tried it, but unsuccesfull.

Thanks,
Shiva.

**Comment by aylashiv** [comment]
Yes I'm using remote_at Sample common Program, the Sample Works expected wihout modifying the xbee_device.c File, I want to Enable XBEE_DEVICE_VERBOSE in xbee_device.c source file were i'm unable to do and want to have console prints in xbee_frame_dump_modem_status() function, I tried it, but unsuccesfull.

Thanks,
Shiva.

**Comment by tomlogic** [comment]
I think you can just pass that macro definition to `make`, and have the C compiler use it.

`make remote_at CFLAGS=-DXBEE_DEVICE_VERBOSE=1`

Make passes `CFLAGS` to the C compiler, and it interprets the `-D` option to define the macro.

**Comment by aylashiv** [comment]
Passed the Above make command it shows a compile error of "unknown target" A screenshot attached.
![Screenshot from 2024-03-14 13-30-30](https://github.com/digidotcom/xbee_ansic_library/assets/32709434/0af390a9-c262-4f54-b9ef-004d073f2203)
Thanks,
Shiva.

**Comment by tomlogic** [comment]
You shouldn't have a `platform.h` in `ports/posix`.  `include/xbee/platform.h` should automatically bring in `ports/posix/platform_config.h`.  Try compiling with a fresh, unmodified repository.

**Comment by aylashiv** [comment]
Though I have the same un-modified also, it reflects this error, Attached the screenshot
**ports/posix/xbee_platform_posix.c:25:10: fatal error: xbee/platform.h: No such file or directory** 
![Screenshot from 2024-03-14 16-54-38](https://github.com/digidotcom/xbee_ansic_library/assets/32709434/b6434520-f706-48b1-a1e8-638e35be1c8b)

**Comment by tomlogic** [comment]
OK, defining `CFLAGS` on the command line overrides the setting inside the Makefile.  My test compile passed because I didn't `make clean` beforehand.

Maybe the easiest solution is to edit the Makefile and add that macro to the `DEFINE` definition.

`DEFINE = -DPOSIX -DXBEE_DEVICE_VERBOSE`

Do a `make clean` and then `make`.

**Comment by aylashiv** [comment]
Its Working !!! Edited the Makefile for the above changes.

Thanks,
Shiva.A

**Comment by aylashiv** [comment]
Hi, I have the issue still in having the custom prints in xbee_device.c file, which i'm unable to get it, that did not solved yet.

Thanks,
Shiva.

**Comment by tomlogic** [comment]
It doesn't sound like it's an issue with this code, but with your attempts to have custom output from within `xbee_device.c`.

What is your expectation?  What have you tried so far?  You mention "custom prints".  What do you want to print, and when do you want it to print?

**Comment by samhitha-emb** [comment]
I want to write the Xbee  Mac address of the Xbee device attached locally to the machine to a file in my Machine.

**Comment by aylashiv** [comment]
I want to write the Xbee Mac address of the Xbee device attached locally to the machine to a file in my Machine

**Comment by tomlogic** [comment]
Let's move this to issue #40.
