### ISSUE TITLE
Error -110 waiting for query to complete.

### ISSUE THREAD

**Issue by aylashiv** [digidotcom/xbee_ansic_library#41]
Hi,
I understand this Error was addressed longback, but its frequent in my case with the device i'm using XBee-Pro-900HP, Unable to findout what actually causing the issue. And unable to find the solution as well, as per the solution to the issue https://github.com/digidotcom/xbee_ansic_library/issues/18  

Thanks.

**Comment by tomlogic** [comment]
Does it work with XCTU?  Do you have `ATAP` set to 1?  Do you have the correct baud rate?  Correct serial port?

Can you use the `xbee_term` sample to communicate with the module?  If you have the correct baud rate, you should be able to send a sequence of `+++` to enter "AT command mode" and have it respond with OK.  You can then send AT commands (like `ATSH` and `ATSL` to get the high and low 32-bit values of the serial number).

**Comment by aylashiv** [comment]
Yeah it works well with XCTU, and all other parameters defined above are well taken care of.im using POSIX platform. I have run transparent-client program.

**Comment by tomlogic** [comment]
Does the `atinter` sample work?  If so, then the serial port and XBee module configuration are good.

If not, try using `xbee_term` to verify basic communications to the module.  If that fails, a program like `minicom` might be good to verify that serial communications works at the hardware level.

Is the module wired to TTL-level I/O pins of the BeagleBone, or are you using a USB adapter?

For the "transparent client" sample, you need to verify that the modules are joined to the same network in order for Node Discovery to work.

**Comment by aylashiv** [comment]
could you help me understand the usage of the xbee_term code, were I'm unable to see any document to set the parameters.

**Comment by tomlogic** [comment]
If you build and run the `xbee_term` sample, it takes similar parameters as `atinter` for specifying the serial port and baud rate.

    ./xbee_term /dev/ttyS001 115200

It then prints instructions before providing a simple terminal interface.

    Simple XBee Terminal
    CTRL-X to EXIT, CTRL-K toggles break, CTRL-R toggles RTS, TAB changes bps.

**Comment by aylashiv** [comment]
Im able to do the step as you have mentioned , the thing that TAB function do is changing the Xbee Baud/xbee driver setting to that Baud?

**Comment by tomlogic** [comment]
Yes, while the program is running you can use TAB to change the baud rate.  This is useful in some modules where you're trying to enter the bootloader, which operates at a fixed speed.  Or if you're trying to get a module to respond and you don't know what its settings are.

If you can't get the XBee to respond in `xbee_term`, you have a serial port problem that you need to resolve before any of the samples that make use of API mode will work.

**Comment by aylashiv** [comment]
Xbee_term will work in AT or API mode? Because while I could able to change the Baud rate and trying to enter to AT mode by issuing +++ sequence, and issued AT , I see no response.

**Comment by tomlogic** [comment]
Even when you're in API mode, the `+++` escape sequence should work to allow entry of AT commands.

Are you hard-wiring the XBee module to I/O pins of the BeagleBone?  Did you remember to connect ground as well?  Perhaps you have TX and RX swapped?  Remember that TX from one device should go to RX of the other.

**Comment by samhitha-emb** [comment]
The connection is from RX to TX and vice versa and Gnd is connected as well. Y its not entering AT mode Yeah.. even I'm surprised...

**Comment by tomlogic** [comment]
Another troubleshooting step is to disconnect the XBee module and loopback your TX pin to RX.  In the terminal emulator, you should see an echo back of any character sent out.

If it fails, you have a hardware issue unrelated to the XBee.

**Comment by samhitha-emb** [comment]
Done Echo !!! This will be our inital steps of test cases for UART bringup, it was tested long back itself.  As per Sample Programs Info in SDK **XBee Term: Simple, stand-alone terminal emulator to interact with a module's bootloader or its regular firmware in command mode** Here its mentioned Command Mode, which commands ? AT?

**Comment by tomlogic** [comment]
The XBee-PRO 900HP uses 3V I/O.  What does your embedded platform use?  If it's 5V, it won't work correctly.

You could try swapping TX and RX connections to verify that they're correct.

You said the module worked with XCTU, so you know the baud rate.  In case this is a hardware flow-control issue, you could try temporarily setting `ATD6` and `ATD7` to 0 within XCTU before performing further tests with `xbee_term` on your hardware.

With the correct baud rate set in `xbee_term`, you should be able to enter this sequence and receive an `OK` response:

* Wait one second.
* Send `+++` (and **do not** hit return).
* Wait one second.

Here's [Digi's documentation on entering AT command mode](https://www.digi.com/resources/documentation/digidocs/90002173/#tasks/t_enter_cmd_mode.htm?TocPath=Modes%257CModes%2520of%2520operation%257CCommand%2520mode%257C_____1).

**Comment by tomlogic** [comment]
@aylashiv / @samhitha-emb : I'm closing this issue since there hasn't been any followup since my last message.
